/**
 * Your application code goes here<br>
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */


package userclasses;

import generated.StateMachineBase;
import com.codename1.ui.*; 
import com.codename1.ui.events.*;
import com.codename1.ui.util.Resources;
import com.codename1.capture.Capture;

/**
 *
 * @author Your name here
 */
public class StateMachine extends StateMachineBase {
    public StateMachine(String resFile) {
        super(resFile);
        // do not modify, write code in initVars and initialize class members there,
        // the constructor might be invoked too late due to race conditions that might occur
    }
    
    /**
     * this method should be used to initialize variables instead of
     * the constructor/class scope to avoid race conditions
     */
    protected void initVars(Resources res) {
    }


    @Override
    protected void onMain_CaptureButtonAction(Component c, ActionEvent event) {
    String s = Capture.capturePhoto(Display.getInstance().getDisplayWidth(), -1);
            if (s != null) {
                try {
                    Image img = Image.createImage(s);
                    findPhotoLabel().setIcon(img);
                    c.getComponentForm().revalidate();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
        } 
    }

    @Override
    protected void onMain_RefreshSliderButtonAction(Component c, ActionEvent event) {
        findSlider().setProgress((int)Display.getInstance().getFrameRate());
    }
}
